In [1]:
import pandas as pd
from bs4 import BeautifulSoup
import requests

In [3]:
url = 'https://www.laalmanac.com/employment/em03.php'

page = requests.get(url)

soup = BeautifulSoup(page.text, 'html')

In [5]:
table = soup.find('table')

In [9]:
column_data = table.find_all('tr')

In [11]:
list = []
for row in column_data[1:]:
    row_data = row.find_all('td')
    individual_row_data = [data.text.strip() for data in row_data]
    list.append(individual_row_data)

list

[[],
 ['Los Angeles County', '5,123,800', '4,815,500', '308,300', '6.0%'],
 ['Acton†', '3,200', '3,100', '100', '2.8%'],
 ['Agoura Hills', '11,400', '10,800', '600', '5.1%'],
 ['Alhambra', '46,400', '44,100', '2,300', '5.0%'],
 ['Alondra Park†', '4,100', '3,900', '200', '4.0%'],
 [],
 [],
 ['Altadena†', '22,000', '20,700', '1,300', '6.1%'],
 ['Arcadia', '29,200', '27,800', '1,400', '4.8%'],
 ['Artesia', '7,900', '7,300', '600', '7.5%'],
 ['Avalon', '2,000', '2,000', '0', '0.0%'],
 ['Avocado Heights†', '6,900', '6,500', '400', '5.8%'],
 [],
 [],
 ['Azusa', '25,400', '23,900', '1,400', '5.7%'],
 ['Baldwin Park', '34,600', '32,500', '2,100', '6.0%'],
 ['Bell', '15,100', '14,100', '1,000', '6.4%'],
 ['Bell Gardens', '18,000', '16,800', '1,200', '6.5%'],
 ['Bellflower', '36,300', '33,900', '2,400', '6.7%'],
 [],
 [],
 ['Beverly Hills', '18,000', '17,100', '900', '5.1%'],
 ['Bradbury', '400', '300', '0', '8.9%'],
 ['Burbank', '59,700', '55,400', '4,300', '7.3%'],
 ['Calabasas', '11,800', '10,800', '1,000', '8.6%'],
 ['Carson', '45,800', '43,100', '2,700', '6.0%'],
 [],
 [],
 ['Cerritos', '25,000', '23,700', '1,300', '5.2%'],
 ['Charter Oak†', '5,300', '5,000', '300', '6.0%'],
 ['Citrus†', '5,600', '5,300', '300', '5.4%'],
 ['Claremont', '17,000', '16,000', '1,000', '5.8%'],
 ['Commerce', '5,500', '5,100', '400', '6.4%'],
 [],
 [],
 ['Compton', '39,000', '35,900', '3,100', '7.8%'],
 ['Covina', '24,200', '22,600', '1,500', '6.3%'],
 ['Cudahy', '10,000', '9,400', '600', '6.4%'],
 ['Culver City', '23,100', '21,700', '1,300', '5.7%'],
 ['Del Aire†', '5,500', '5,300', '200', '3.3%'],
 [],
 [],
 ['Desert View Highlands†', '1,400', '1,300', '100', '6.6%'],
 ['Diamond Bar', '30,100', '28,700', '1,500', '4.8%'],
 ['Downey', '56,800', '53,700', '3,200', '5.6%'],
 ['Duarte', '11,300', '10,700', '600', '5.6%'],
 ['East Los Angeles†', '55,900', '52,500', '3,300', '6.0%'],
 [],
 [],
 ['East Pasadena†', '2,700', '2,700', '100', '2.9%'],
 ['East San Gabriel†', '11,600', '10,900', '800', '6.4%'],
 ['El Monte', '51,200', '48,300', '2,900', '5.7%'],
 ['El Segundo', '10,200', '9,700', '500', '5.1%'],
 ['Florence-Graham†', '28,600', '26,200', '2,400', '8.4%'],
 [],
 [],
 ['Gardena', '30,300', '28,400', '1,800', '6.1%'],
 ['Glendale', '104,000', '97,900', '6,100', '5.8%'],
 ['Glendora', '25,800', '24,500', '1,400', '5.3%'],
 ['Hacienda Heights†', '27,200', '25,900', '1,300', '4.8%'],
 ['Hawaiian Gardens', '6,700', '6,400', '300', '4.8%'],
 [],
 [],
 ['Hawthorne', '43,900', '41,400', '2,600', '5.8%'],
 ['Hermosa Beach', '11,700', '11,300', '400', '3.6%'],
 ['Hidden Hills', '900', '900', '0', '3.8%'],
 ['Huntington Park', '26,300', '24,800', '1,500', '5.7%'],
 ['Industry', '100', '100', '0', '6.6%'],
 [],
 [],
 ['Inglewood', '52,800', '49,100', '3,700', '7.1%'],
 ['Irwindale', '700', '700', '0', '5.4%'],
 ['La Cañada Flintridge', '8,900', '8,600', '400', '4.2%'],
 ['La Crescenta-Montrose†', '10,100', '9,400', '600', '6.3%'],
 ['La Habra Heights', '3,000', '2,900', '100', '2.4%'],
 [],
 [],
 ['La Mirada', '24,100', '22,700', '1,400', '5.7%'],
 ['La Puente', '19,000', '17,900', '1,100', '5.7%'],
 ['La Verne', '16,300', '15,400', '900', '5.3%'],
 ['Ladera Heights†', '3,100', '3,000', '200', '5.5%'],
 ['Lake Los Angeles†', '4,100', '3,800', '300', '7.3%'],
 [],
 [],
 ['Lakewood', '42,500', '40,300', '2,300', '5.3%'],
 ['Lancaster', '65,200', '59,800', '5,300', '8.2%'],
 ['Lawndale', '16,500', '15,600', '900', '5.3%'],
 ['Lennox†', '11,500', '10,800', '700', '6.2%'],
 ['Littlerock†', '400', '400', '0', '10.1%'],
 [],
 [],
 ['Lomita', '11,100', '10,800', '300', '2.5%'],
 ['Long Beach', '237,000', '222,700', '14,400', '6.1%'],
 ['Los Angeles', '2,107,400', '1,978,300', '129,000', '6.1%'],
 ['Lynwood', '28,300', '26,400', '1,900', '6.7%'],
 ['Malibu', '5,400', '5,200', '200', '4.1%'],
 [],
 [],
 ['Manhattan Beach', '19,400', '18,500', '800', '4.3%'],
 ['Marina del Rey†', '7,100', '6,800', '300', '4.1%'],
 ['Mayflower Village†', '2,900', '2,800', '100', '3.5%'],
 ['Maywood', '12,400', '11,600', '800', '6.1%'],
 ['Monrovia', '21,900', '20,800', '1,100', '5.1%'],
 [],
 [],
 ['Montebello', '29,000', '27,200', '1,800', '6.2%'],
 ['Monterey Park', '29,300', '27,800', '1,500', '5.1%'],
 ['North El Monte†', '2,000', '2,000', '100', '2.5%'],
 ['Norwalk', '50,300', '47,200', '3,100', '6.2%'],
 ['Palmdale', '63,500', '58,300', '5,200', '8.1%'],
 [],
 [],
 ['Palos Verdes Estates', '5,600', '5,400', '200', '2.8%'],
 ['Paramount', '24,600', '23,000', '1,700', '6.8%'],
 ['Pasadena', '80,500', '76,100', '4,300', '5.4%'],
 ['Pico Rivera', '30,200', '28,300', '1,900', '6.4%'],
 ['Pomona', '68,200', '63,700', '4,500', '6.5%'],
 [],
 [],
 ['Quartz Hill†', '4,700', '4,500', '200', '4.2%'],
 ['Rancho Palos Verdes', '19,500', '18,500', '1,000', '4.9%'],
 ['Redondo Beach', '41,000', '38,900', '2,100', '5.1%'],
 ['Rolling Hills', '600', '500', '0', '6.2%'],
 ['Rolling Hills Estates', '3,500', '3,300', '200', '6.2%'],
 [],
 [],
 ['Rosemead', '25,100', '23,700', '1,400', '5.5%'],
 ['Rowland Heights†', '24,300', '22,900', '1,500', '6.0%'],
 ['San Dimas', '17,800', '16,900', '900', '5.1%'],
 ['San Fernando', '12,000', '11,400', '600', '4.6%'],
 ['San Gabriel', '21,400', '20,400', '1,000', '4.6%'],
 [],
 [],
 ['San Marino', '5,800', '5,600', '200', '3.0%'],
 ['Santa Clarita', '115,200', '108,700', '6,400', '5.6%'],
 ['Santa Fe Springs', '9,000', '8,700', '400', '4.0%'],
 ['Santa Monica', '56,700', '53,400', '3,300', '5.8%'],
 ['Sierra Madre', '6,200', '5,900', '200', '4.0%'],
 [],
 [],
 ['Signal Hill', '6,200', '6,000', '200', '3.7%'],
 ['South El Monte', '9,000', '8,600', '400', '4.8%'],
 ['South Gate', '42,800', '40,200', '2,600', '6.0%'],
 ['South Pasadena', '14,900', '14,100', '900', '5.9%'],
 ['South San Gabriel†', '3,700', '3,600', '100', '3.7%'],
 [],
 [],
 ['South San Jose Hills†', '9,900', '9,200', '700', '7.0%'],
 ['South Whittier†', '29,400', '28,100', '1,300', '4.5%'],
 ['Temple City', '18,200', '17,300', '900', '5.1%'],
 ['Torrance', '77,700', '73,800', '3,800', '4.9%'],
 ['Val Verde†', '1,600', '1,500', '100', '5.9%'],
 [],
 [],
 ['Valinda†', '11,600', '11,000', '600', '5.6%'],
 ['Vernon', '100', '100', '0', '6.9%'],
 ['View Park-Windsor Hills†', '5,900', '5,400', '500', '8.9%'],
 ['Walnut', '16,000', '15,200', '800', '4.8%'],
 ['Walnut Park†', '8,300', '7,700', '600', '6.9%'],
 [],
 [],
 ['West Athens†', '4,700', '4,200', '500', '10.2%'],
 ['West Carson†', '11,700', '11,100', '600', '5.2%'],
 ['West Covina', '52,300', '49,400', '2,900', '5.6%'],
 ['West Hollywood', '26,500', '24,800', '1,700', '6.5%'],
 ['West Puente Valley†', '10,900', '10,200', '700', '6.4%'],
 [],
 [],
 ['West Whittier-Los Nietos†', '12,300', '11,800', '500', '4.3%'],
 ['Westlake Village', '3,900', '3,800', '100', '1.9%'],
 ['Westmont†', '15,400', '13,900', '1,500', '9.8%'],
 ['Whittier', '43,100', '40,700', '2,500', '5.7%'],
 ['Willowbrook†', '10,200', '9,400', '900', '8.5%']]

In [13]:
list
filtered_list = [item for item in list if item]

In [17]:
filtered_list

[['Los Angeles County', '5,123,800', '4,815,500', '308,300', '6.0%'],
 ['Acton†', '3,200', '3,100', '100', '2.8%'],
 ['Agoura Hills', '11,400', '10,800', '600', '5.1%'],
 ['Alhambra', '46,400', '44,100', '2,300', '5.0%'],
 ['Alondra Park†', '4,100', '3,900', '200', '4.0%'],
 ['Altadena†', '22,000', '20,700', '1,300', '6.1%'],
 ['Arcadia', '29,200', '27,800', '1,400', '4.8%'],
 ['Artesia', '7,900', '7,300', '600', '7.5%'],
 ['Avalon', '2,000', '2,000', '0', '0.0%'],
 ['Avocado Heights†', '6,900', '6,500', '400', '5.8%'],
 ['Azusa', '25,400', '23,900', '1,400', '5.7%'],
 ['Baldwin Park', '34,600', '32,500', '2,100', '6.0%'],
 ['Bell', '15,100', '14,100', '1,000', '6.4%'],
 ['Bell Gardens', '18,000', '16,800', '1,200', '6.5%'],
 ['Bellflower', '36,300', '33,900', '2,400', '6.7%'],
 ['Beverly Hills', '18,000', '17,100', '900', '5.1%'],
 ['Bradbury', '400', '300', '0', '8.9%'],
 ['Burbank', '59,700', '55,400', '4,300', '7.3%'],
 ['Calabasas', '11,800', '10,800', '1,000', '8.6%'],
 ['Carson', '45,800', '43,100', '2,700', '6.0%'],
 ['Cerritos', '25,000', '23,700', '1,300', '5.2%'],
 ['Charter Oak†', '5,300', '5,000', '300', '6.0%'],
 ['Citrus†', '5,600', '5,300', '300', '5.4%'],
 ['Claremont', '17,000', '16,000', '1,000', '5.8%'],
 ['Commerce', '5,500', '5,100', '400', '6.4%'],
 ['Compton', '39,000', '35,900', '3,100', '7.8%'],
 ['Covina', '24,200', '22,600', '1,500', '6.3%'],
 ['Cudahy', '10,000', '9,400', '600', '6.4%'],
 ['Culver City', '23,100', '21,700', '1,300', '5.7%'],
 ['Del Aire†', '5,500', '5,300', '200', '3.3%'],
 ['Desert View Highlands†', '1,400', '1,300', '100', '6.6%'],
 ['Diamond Bar', '30,100', '28,700', '1,500', '4.8%'],
 ['Downey', '56,800', '53,700', '3,200', '5.6%'],
 ['Duarte', '11,300', '10,700', '600', '5.6%'],
 ['East Los Angeles†', '55,900', '52,500', '3,300', '6.0%'],
 ['East Pasadena†', '2,700', '2,700', '100', '2.9%'],
 ['East San Gabriel†', '11,600', '10,900', '800', '6.4%'],
 ['El Monte', '51,200', '48,300', '2,900', '5.7%'],
 ['El Segundo', '10,200', '9,700', '500', '5.1%'],
 ['Florence-Graham†', '28,600', '26,200', '2,400', '8.4%'],
 ['Gardena', '30,300', '28,400', '1,800', '6.1%'],
 ['Glendale', '104,000', '97,900', '6,100', '5.8%'],
 ['Glendora', '25,800', '24,500', '1,400', '5.3%'],
 ['Hacienda Heights†', '27,200', '25,900', '1,300', '4.8%'],
 ['Hawaiian Gardens', '6,700', '6,400', '300', '4.8%'],
 ['Hawthorne', '43,900', '41,400', '2,600', '5.8%'],
 ['Hermosa Beach', '11,700', '11,300', '400', '3.6%'],
 ['Hidden Hills', '900', '900', '0', '3.8%'],
 ['Huntington Park', '26,300', '24,800', '1,500', '5.7%'],
 ['Industry', '100', '100', '0', '6.6%'],
 ['Inglewood', '52,800', '49,100', '3,700', '7.1%'],
 ['Irwindale', '700', '700', '0', '5.4%'],
 ['La Cañada Flintridge', '8,900', '8,600', '400', '4.2%'],
 ['La Crescenta-Montrose†', '10,100', '9,400', '600', '6.3%'],
 ['La Habra Heights', '3,000', '2,900', '100', '2.4%'],
 ['La Mirada', '24,100', '22,700', '1,400', '5.7%'],
 ['La Puente', '19,000', '17,900', '1,100', '5.7%'],
 ['La Verne', '16,300', '15,400', '900', '5.3%'],
 ['Ladera Heights†', '3,100', '3,000', '200', '5.5%'],
 ['Lake Los Angeles†', '4,100', '3,800', '300', '7.3%'],
 ['Lakewood', '42,500', '40,300', '2,300', '5.3%'],
 ['Lancaster', '65,200', '59,800', '5,300', '8.2%'],
 ['Lawndale', '16,500', '15,600', '900', '5.3%'],
 ['Lennox†', '11,500', '10,800', '700', '6.2%'],
 ['Littlerock†', '400', '400', '0', '10.1%'],
 ['Lomita', '11,100', '10,800', '300', '2.5%'],
 ['Long Beach', '237,000', '222,700', '14,400', '6.1%'],
 ['Los Angeles', '2,107,400', '1,978,300', '129,000', '6.1%'],
 ['Lynwood', '28,300', '26,400', '1,900', '6.7%'],
 ['Malibu', '5,400', '5,200', '200', '4.1%'],
 ['Manhattan Beach', '19,400', '18,500', '800', '4.3%'],
 ['Marina del Rey†', '7,100', '6,800', '300', '4.1%'],
 ['Mayflower Village†', '2,900', '2,800', '100', '3.5%'],
 ['Maywood', '12,400', '11,600', '800', '6.1%'],
 ['Monrovia', '21,900', '20,800', '1,100', '5.1%'],
 ['Montebello', '29,000', '27,200', '1,800', '6.2%'],
 ['Monterey Park', '29,300', '27,800', '1,500', '5.1%'],
 ['North El Monte†', '2,000', '2,000', '100', '2.5%'],
 ['Norwalk', '50,300', '47,200', '3,100', '6.2%'],
 ['Palmdale', '63,500', '58,300', '5,200', '8.1%'],
 ['Palos Verdes Estates', '5,600', '5,400', '200', '2.8%'],
 ['Paramount', '24,600', '23,000', '1,700', '6.8%'],
 ['Pasadena', '80,500', '76,100', '4,300', '5.4%'],
 ['Pico Rivera', '30,200', '28,300', '1,900', '6.4%'],
 ['Pomona', '68,200', '63,700', '4,500', '6.5%'],
 ['Quartz Hill†', '4,700', '4,500', '200', '4.2%'],
 ['Rancho Palos Verdes', '19,500', '18,500', '1,000', '4.9%'],
 ['Redondo Beach', '41,000', '38,900', '2,100', '5.1%'],
 ['Rolling Hills', '600', '500', '0', '6.2%'],
 ['Rolling Hills Estates', '3,500', '3,300', '200', '6.2%'],
 ['Rosemead', '25,100', '23,700', '1,400', '5.5%'],
 ['Rowland Heights†', '24,300', '22,900', '1,500', '6.0%'],
 ['San Dimas', '17,800', '16,900', '900', '5.1%'],
 ['San Fernando', '12,000', '11,400', '600', '4.6%'],
 ['San Gabriel', '21,400', '20,400', '1,000', '4.6%'],
 ['San Marino', '5,800', '5,600', '200', '3.0%'],
 ['Santa Clarita', '115,200', '108,700', '6,400', '5.6%'],
 ['Santa Fe Springs', '9,000', '8,700', '400', '4.0%'],
 ['Santa Monica', '56,700', '53,400', '3,300', '5.8%'],
 ['Sierra Madre', '6,200', '5,900', '200', '4.0%'],
 ['Signal Hill', '6,200', '6,000', '200', '3.7%'],
 ['South El Monte', '9,000', '8,600', '400', '4.8%'],
 ['South Gate', '42,800', '40,200', '2,600', '6.0%'],
 ['South Pasadena', '14,900', '14,100', '900', '5.9%'],
 ['South San Gabriel†', '3,700', '3,600', '100', '3.7%'],
 ['South San Jose Hills†', '9,900', '9,200', '700', '7.0%'],
 ['South Whittier†', '29,400', '28,100', '1,300', '4.5%'],
 ['Temple City', '18,200', '17,300', '900', '5.1%'],
 ['Torrance', '77,700', '73,800', '3,800', '4.9%'],
 ['Val Verde†', '1,600', '1,500', '100', '5.9%'],
 ['Valinda†', '11,600', '11,000', '600', '5.6%'],
 ['Vernon', '100', '100', '0', '6.9%'],
 ['View Park-Windsor Hills†', '5,900', '5,400', '500', '8.9%'],
 ['Walnut', '16,000', '15,200', '800', '4.8%'],
 ['Walnut Park†', '8,300', '7,700', '600', '6.9%'],
 ['West Athens†', '4,700', '4,200', '500', '10.2%'],
 ['West Carson†', '11,700', '11,100', '600', '5.2%'],
 ['West Covina', '52,300', '49,400', '2,900', '5.6%'],
 ['West Hollywood', '26,500', '24,800', '1,700', '6.5%'],
 ['West Puente Valley†', '10,900', '10,200', '700', '6.4%'],
 ['West Whittier-Los Nietos†', '12,300', '11,800', '500', '4.3%'],
 ['Westlake Village', '3,900', '3,800', '100', '1.9%'],
 ['Westmont†', '15,400', '13,900', '1,500', '9.8%'],
 ['Whittier', '43,100', '40,700', '2,500', '5.7%'],
 ['Willowbrook†', '10,200', '9,400', '900', '8.5%']]

In [39]:
df = pd.DataFrame(filtered_list, columns=['City', 'Labor Force', 'Employed', 'Unemployed', 'Unemployed Rate (%)'])

In [25]:
df

,City,Labor Force,Employed,Unemployed,Unemployed Rate
0,Los Angeles County,"5,123,800","4,815,500","308,300",6.0%
1,Acton†,"3,200","3,100",100,2.8%
2,Agoura Hills,"11,400","10,800",600,5.1%
3,Alhambra,"46,400","44,100","2,300",5.0%
4,Alondra Park†,"4,100","3,900",200,4.0%
...,...,...,...,...,...
120,West Whittier-Los Nietos†,"12,300","11,800",500,4.3%
121,Westlake Village,"3,900","3,800",100,1.9%
122,Westmont†,"15,400","13,900","1,500",9.8%
123,Whittier,"43,100","40,700","2,500",5.7%
124,Willowbrook†,"10,200","9,400",900,8.5%

In [41]:
df['City'] = df['City'].str.replace('†', '', regex=False)

In [29]:
df

,City,Labor Force,Employed,Unemployed,Unemployed Rate
0,Los Angeles County,"5,123,800","4,815,500","308,300",6.0%
1,Acton,"3,200","3,100",100,2.8%
2,Agoura Hills,"11,400","10,800",600,5.1%
3,Alhambra,"46,400","44,100","2,300",5.0%
4,Alondra Park,"4,100","3,900",200,4.0%
...,...,...,...,...,...
120,West Whittier-Los Nietos,"12,300","11,800",500,4.3%
121,Westlake Village,"3,900","3,800",100,1.9%
122,Westmont,"15,400","13,900","1,500",9.8%
123,Whittier,"43,100","40,700","2,500",5.7%
124,Willowbrook,"10,200","9,400",900,8.5%

In [43]:
def clean_and_convert(value):
    value = value.replace(',', '').rstrip('%').strip()  # Remove commas, trailing '%', and whitespace
    return pd.to_numeric(value, errors='coerce')  # Convert to numeric, setting errors to NaN
df.loc[:, df.columns != 'City'] = df.loc[:, df.columns != 'City'].applymap(clean_and_convert)

C:\Users\pminh\AppData\Local\Temp\ipykernel_16948\3998214152.py:4: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.loc[:, df.columns != 'City'] = df.loc[:, df.columns != 'City'].applymap(clean_and_convert)

In [45]:
df.to_csv('employment.csv', index=False)

In [37]:
df

                         City Labor Force Employed Unemployed Unemployed Rate
0          Los Angeles County     5123800  4815500     308300             6.0
1                       Acton        3200     3100        100             2.8
2                Agoura Hills       11400    10800        600             5.1
3                    Alhambra       46400    44100       2300             5.0
4                Alondra Park        4100     3900        200             4.0
..                        ...         ...      ...        ...             ...
120  West Whittier-Los Nietos       12300    11800        500             4.3
121          Westlake Village        3900     3800        100             1.9
122                  Westmont       15400    13900       1500             9.8
123                  Whittier       43100    40700       2500             5.7
124               Willowbrook       10200     9400        900             8.5

[125 rows x 5 columns]